USE [master]
GO

/****** Object:  Database [МагазинЭлектроники]    Script Date: 03.04.2022 18:03:15 ******/
CREATE DATABASE [МагазинЭлектроники]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'МагазинЭлектроники', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\МагазинЭлектроники.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'МагазинЭлектроники_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\МагазинЭлектроники_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [МагазинЭлектроники] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [МагазинЭлектроники].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [МагазинЭлектроники] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [МагазинЭлектроники] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [МагазинЭлектроники] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [МагазинЭлектроники] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [МагазинЭлектроники] SET ARITHABORT OFF 
GO

ALTER DATABASE [МагазинЭлектроники] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [МагазинЭлектроники] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [МагазинЭлектроники] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [МагазинЭлектроники] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [МагазинЭлектроники] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [МагазинЭлектроники] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [МагазинЭлектроники] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [МагазинЭлектроники] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [МагазинЭлектроники] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [МагазинЭлектроники] SET  ENABLE_BROKER 
GO

ALTER DATABASE [МагазинЭлектроники] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [МагазинЭлектроники] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [МагазинЭлектроники] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [МагазинЭлектроники] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [МагазинЭлектроники] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [МагазинЭлектроники] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [МагазинЭлектроники] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [МагазинЭлектроники] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [МагазинЭлектроники] SET  MULTI_USER 
GO

ALTER DATABASE [МагазинЭлектроники] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [МагазинЭлектроники] SET DB_CHAINING OFF 
GO

ALTER DATABASE [МагазинЭлектроники] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [МагазинЭлектроники] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [МагазинЭлектроники] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [МагазинЭлектроники] SET  READ_WRITE 
GO

