//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electronics_Store
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class МагазинЭлектроникиEntities : DbContext
    {
        private static МагазинЭлектроникиEntities _context;
        public static МагазинЭлектроникиEntities GetContext()
        {
            if (_context == null)
                _context = new МагазинЭлектроникиEntities();
            return _context;
        }
        public МагазинЭлектроникиEntities()
            : base("name=МагазинЭлектроникиEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Пользователь> Пользователь { get; set; }
        public virtual DbSet<Поставка> Поставка { get; set; }
        public virtual DbSet<Продажа> Продажа { get; set; }
        public virtual DbSet<Сотрудник> Сотрудник { get; set; }
        public virtual DbSet<Товар> Товар { get; set; }
    }
}
