//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electronics_Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class TovarSale
    {
        public int id { get; set; }
        public int idTovar { get; set; }
        public int idSell { get; set; }
        public int count { get; set; }
    
        public virtual Sell Sell { get; set; }
        public virtual Tovar Tovar { get; set; }
    }
}
