//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electronics_Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудник
    {
        public int id { get; set; }
        public string fullname { get; set; }
        public string name { get; set; }
        public string patronymic { get; set; }
        public int phone { get; set; }
        public byte[] photo { get; set; }
    
        public virtual Пользователь Пользователь { get; set; }
    }
}
